### ISSUE TITLE
workerify keyword no longer working

### ISSUE THREAD

**Issue by bcomnes** [shama/workerify#22]
Maybe we can just remove that option.

```
> workerify@1.1.0 test /Users/bret/repos/workerify
> browserify test/test.js -t ./ -o test/out.js

/Users/bret/repos/workerify/node_modules/falafel/node_modules/acorn/dist/acorn.js:2750
  throw err
  ^

SyntaxError: Unexpected token (24:26)
    at Parser.pp$4.raise (/Users/bret/repos/workerify/node_modules/falafel/node_modules/acorn/dist/acorn.js:2748:13)
    at Parser.pp.unexpected (/Users/bret/repos/workerify/node_modules/falafel/node_modules/acorn/dist/acorn.js:644:8)
    at Parser.pp.semicolon (/Users/bret/repos/workerify/node_modules/falafel/node_modules/acorn/dist/acorn.js:621:64)
    at Parser.pp$1.parseVarStatement (/Users/bret/repos/workerify/node_modules/falafel/node_modules/acorn/dist/acorn.js:1027:8)
    at Parser.pp$1.parseStatement (/Users/bret/repos/workerify/node_modules/falafel/node_modules/acorn/dist/acorn.js:785:17)
    at Parser.pp$1.parseBlock (/Users/bret/repos/workerify/node_modules/falafel/node_modules/acorn/dist/acorn.js:1104:23)
    at Parser.pp$3.parseFunctionBody (/Users/bret/repos/workerify/node_modules/falafel/node_modules/acorn/dist/acorn.js:2591:22)
    at Parser.pp$1.parseFunction (/Users/bret/repos/workerify/node_modules/falafel/node_modules/acorn/dist/acorn.js:1211:8)
    at Parser.pp$3.parseExprAtom (/Users/bret/repos/workerify/node_modules/falafel/node_modules/acorn/dist/acorn.js:2176:17)
    at Parser.pp$3.parseExprSubscripts (/Users/bret/repos/workerify/node_modules/falafel/node_modules/acorn/dist/acorn.js:2039:19)
npm ERR! Test failed.  See above for more details.
```

**Comment by shama** [comment]
Yeah removing it sounds good to me as it's super non-standard.
